### ISSUE TITLE
Error on adding a new domain

### ISSUE THREAD

**Issue by imangm** [stormkit-io/app-stormkit-io#117] opened 2021-02-16 17:47 UTC
When I want to use a custom domain, If I add it in the "Configure Domain" section, but don't verify it immediately (I have to wait for DNS records to propagate), if I return to this section later to validate the domain, the following error will appear:

![domain-error](https://user-images.githubusercontent.com/4434009/108100699-834c7580-709b-11eb-8985-8af0e35a6583.jpg)

The error seems to be because of this API request:

```
Request URL: https://localhost:3000/api/app/XXXXX/envs/production/lookup
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin
```

Meanwhile, if I open the above URL directly in the browser, it returns the following JSON - no 500 error anymore:

```
{"ok":false,"user":false}
```

I also checked it in env variable in frontend and this is its value which includes domain name inside it:

```
"domain":{"name":"myowndomain.com","verified":false,"cname":"myowndomain-com-SOMEID.hosting.stormkit.io."}
```

**Comment by svedova** [comment] 2021-06-16 12:09
```
{"ok":false,"user":false}
```

seems like the session is invalid. I provided a fix a while back to redirect the user to login when the API returns this response. The code is here: https://github.com/stormkit-io/app-stormkit-io/blob/master/src/utils/api/Api.ts#L80

As I can't reproduce this error and it seemed to work for other users lately, I'm going to close this issue. Please feel free to reopen if it happens again 🙏

**Closed by svedova** 2021-06-16 12:09 UTC
